[project]
name = "create-python-app"
version = "0.0.0"
dependencies = [
    "aiohttp>=3.9.5",
    "python-socketio>=5.11.2",
    "yt-dlp>=2024.5.27",
]
requires-python = ">=3.11"
[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool.pdm]
